### ISSUE TITLE
Looking for jekyll themes?

### ISSUE THREAD

**Issue by ngzhio** [Aspiring-Writer/Questmasters-Log#1]
Hi, are you looking for Jekyll themes? I'm the creator of [jekyll-theme-hamilton](https://github.com/ngzhio/jekyll-theme-hamilton), thank you to become the first stargazer of this theme.

**Comment by Aspiring-Writer** [comment]
Oh you're welcome! It's a nice theme. I'm still experimenting with different themes. I was thinking about using jekyll-theme-hamilton for a communal blog I'm working on.

**Comment by ngzhio** [comment]
You're not a programmer, right? Rarely see non-programmers using GitHub

**Comment by ngzhio** [comment]
May I have your email?

**Comment by Aspiring-Writer** [comment]
No, I'm not a programmer, yet. Why do you want my email?

**Comment by ngzhio** [comment]
> No, I'm not a programmer, yet. Why do you want my email?

Yet? So you are studying programming?

Just make friends. I'm interested in your blog content.

**Comment by Aspiring-Writer** [comment]
Yes, I'm very interested in programming. Currently, I'm trying out web development with Jekyll.

I'm sorry, but I don't yet have an email that I can give out. I will have to make one later to associate with my blog.

**Comment by Aspiring-Writer** [comment]
If you still want my email, you can find it under my profile. Keep up the good work my friend!

**Comment by ngzhio** [comment]
> If you still want my email, you can find it under my profile. Keep up the good work my friend!

OK, I saw that. I'll send you emails later.
